// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(config) {
    return config.set({
      basePath: '../..',
      frameworks: ['mocha']
    });
  };

}).call(this);

//# sourceMappingURL=karma.conf.js.map
