// Generated by CoffeeScript 1.9.3
(function() {
  var MonthPeriod, should;

  should = require('should');

  MonthPeriod = require('../../PayrolleeMate.Common/Periods/MonthPeriod');

  describe('MonthPeriod', function() {
    var testPeriodCode402, testPeriodCode501, testPeriodCodeFeb, testPeriodCodeJan;
    testPeriodCodeJan = 201401;
    testPeriodCodeFeb = 201402;
    testPeriodCode501 = 201501;
    testPeriodCode402 = 201402;
    it('Should_Compare_Different_Periods_AsEqual_When_2014_01', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      testPeriodTwo = new MonthPeriod(testPeriodCodeJan);
      return true.should.equal(testPeriodOne.isEqualToPeriod(testPeriodTwo));
    });
    it('Should_Compare_Different_Periods_AsEqual_When_2014_02', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeFeb);
      testPeriodTwo = new MonthPeriod(testPeriodCodeFeb);
      return true.should.equal(testPeriodOne.isEqualToPeriod(testPeriodTwo));
    });
    it('Should_Compare_Different_Periods_SameYear_AsGreater', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      testPeriodTwo = new MonthPeriod(testPeriodCodeFeb);
      (testPeriodTwo.isEqualToPeriod(testPeriodOne)).should.equal(false);
      return (testPeriodTwo.isGreaterToPeriod(testPeriodOne)).should.equal(true);
    });
    it('Should_Compare_Different_Periods_SameYear_AsLess', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      testPeriodTwo = new MonthPeriod(testPeriodCodeFeb);
      (testPeriodOne.isEqualToPeriod(testPeriodTwo)).should.equal(false);
      return (testPeriodOne.isLessToPeriod(testPeriodTwo)).should.equal(true);
    });
    it('Should_Compare_Different_Periods_SameMonth_AsGreater', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      testPeriodTwo = new MonthPeriod(testPeriodCode501);
      (testPeriodTwo.isEqualToPeriod(testPeriodOne)).should.equal(false);
      return (testPeriodTwo.isGreaterToPeriod(testPeriodOne)).should.equal(true);
    });
    it('Should_Compare_Different_Periods_SameMonth_AsLess', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      testPeriodTwo = new MonthPeriod(testPeriodCode501);
      (testPeriodOne.isEqualToPeriod(testPeriodTwo)).should.equal(false);
      return (testPeriodOne.isLessToPeriod(testPeriodTwo)).should.equal(true);
    });
    it('Should_Compare_Different_Periods_DifferentYear_AsGreater', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCode402);
      testPeriodTwo = new MonthPeriod(testPeriodCode501);
      (testPeriodTwo.isEqualToPeriod(testPeriodOne)).should.equal(false);
      return (testPeriodTwo.isGreaterToPeriod(testPeriodOne)).should.equal(true);
    });
    it('Should_Compare_Different_Periods_DifferentYear_AsLess', function() {
      var testPeriodOne, testPeriodTwo;
      testPeriodOne = new MonthPeriod(testPeriodCode402);
      testPeriodTwo = new MonthPeriod(testPeriodCode501);
      (testPeriodOne.isEqualToPeriod(testPeriodTwo)).should.equal(false);
      return (testPeriodOne.isLessToPeriod(testPeriodTwo)).should.equal(true);
    });
    it('Should_Return_Periods_Year_And_Month_2014_01', function() {
      var testPeriodOne;
      testPeriodOne = new MonthPeriod(testPeriodCodeJan);
      (testPeriodOne.Year()).should.equal(2014.);
      (testPeriodOne.Month()).should.equal(1.);
      (testPeriodOne.YearInt()).should.equal(2014.);
      return (testPeriodOne.MonthInt()).should.equal(1.);
    });
    it('Should_Return_Periods_Year_And_Month_2014_02', function() {
      var testPeriodTwo;
      testPeriodTwo = new MonthPeriod(testPeriodCodeFeb);
      (testPeriodTwo.Year()).should.equal(2014.);
      (testPeriodTwo.Month()).should.equal(2.);
      (testPeriodTwo.YearInt()).should.equal(2014.);
      return (testPeriodTwo.MonthInt()).should.equal(2.);
    });
    return it('Should_Return_Periods_Month_And_Year_Descriptions', function() {
      var test_period_402, test_period_501, test_period_feb, test_period_jan;
      test_period_jan = new MonthPeriod(testPeriodCodeJan);
      test_period_feb = new MonthPeriod(testPeriodCodeFeb);
      test_period_501 = new MonthPeriod(testPeriodCode501);
      test_period_402 = new MonthPeriod(testPeriodCode402);
      (test_period_jan.Description()).should.equal("January 2014");
      (test_period_feb.Description()).should.equal("February 2014");
      (test_period_501.Description()).should.equal("January 2015");
      return (test_period_402.Description()).should.equal("February 2014");
    });
  });

}).call(this);

//# sourceMappingURL=TestMonthPeriod.js.map
