// Generated by CoffeeScript 1.9.3
(function() {
  var assert;

  assert = require('assert');

  describe('Test Example', function() {
    return it('should equal false', function() {
      return assert.equal(true, false, 'pass');
    });
  });

}).call(this);

//# sourceMappingURL=TestSpanOfYears.js.map
