// Generated by CoffeeScript 1.9.3
(function() {
  var should;

  should = require('should');

  describe('Test Example', function() {
    return it('should equal true', function() {
      return false.should.equal(true);
    });
  });

}).call(this);

//# sourceMappingURL=TestMonthPeriod.js.map
